title: "EDUC 6144: Learning Sciences"
description: "Past, Present, and Future â€” Spring 2026, Penn GSE"
remote_theme: jekyll/minima
baseurl: "/educ6144"
url: "https://penn-wonderlab.github.io"

header_pages:
  - index.md
  - readings.md
  - assignments.md
  - policies.md

minima:
  skin: classic
