title: "EDUC 6144: Learning Sciences"
description: "Past, Present, and Future â€” Spring 2026, Penn GSE"
theme: minima
baseurl: "/EDUC6144"
url: "https://penn-wonderlab.github.io"

header_pages:
  - index.md
  - readings.md
  - assignments.md
  - policies.md
